{*********************************************************}
{*                    VPSR.INC 1.03                      *}
{*********************************************************}

{* ***** BEGIN LICENSE BLOCK *****                                            *}
{* Version: MPL 1.1                                                           *}
{*                                                                            *}
{* The contents of this file are subject to the Mozilla Public License        *}
{* Version 1.1 (the "License"); you may not use this file except in           *}
{* compliance with the License. You may obtain a copy of the License at       *}
{* http://www.mozilla.org/MPL/                                                *}
{*                                                                            *}
{* Software distributed under the License is distributed on an "AS IS" basis, *}
{* WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License   *}
{* for the specific language governing rights and limitations under the       *}
{* License.                                                                   *}
{*                                                                            *}
{* The Original Code is TurboPower Visual PlanIt                              *}
{*                                                                            *}
{* The Initial Developer of the Original Code is TurboPower Software          *}
{*                                                                            *}
{* Portions created by TurboPower Software Inc. are Copyright (c) 2002        *}
{* TurboPower Software Inc. All Rights Reserved.                              *}
{*                                                                            *}
{* Contributor(s):                                                            *}
{*                                                                            *}
{* ***** END LICENSE BLOCK *****                                              *}

{Visual PlanIt String Resources - To create language specific versions of
 Visual PlanIt controls, translate these strings to the desired language
 and re-compile your application.}

resourcestring
  RSNoneStr                 = '(keine)';
  RSYes                     = 'Y';
  RSNo                      = 'N';
  RSTrue                    = 'T';
  RSFalse                   = 'F';
  RSTallShortChars          = 'Wy';
  RSDelete                  = 'Wollen Sie ';
  RSNotDoneYet              = 'This feature is not implemented at this time.';
  RSNoTimersAvail           = 'keine Window''s-Timer verfuegbar.';
  RSBadTriggerHandle        = 'Invalid trigger handle.';
  RSEditingItems            = 'Folder Items Editor.';
  RSEditingFolders          = 'Folder Editor.';
  RSExclusiveEventConflict  = 'Konflikt mit einem anderen exklusivem Termin.';
  RSBackwardTimesError      = 'Die Endzeit kann nich kleiner als die Startzeit sein.';
  RSDBPostError             = 'Fehler posting data to the database.';
  RSMonthConvertError       = 'Fehler converting the month number.';
  RSInvalidDay              = 'Fehler: fehlerhafter Tag.';
  RSInvalidDate             = 'Fehler: fehlerhaftes Datum.';
  RSInvalidMonth            = 'Fehler: fehlerhafter Monat.';
  RSInvalidMonthName        = 'Fehler: fehlerhafter Monatsname.';
  RSInvalidYear             = 'Fehler: fehlerhafters Jahr.';
  RSDayIsRequired           = 'Fehler: Tag wird benoetigt.';
  RSMonthIsRequired         = 'Fehler: Monat wird benoetigt.';
  RSYearIsRequired          = 'Fehler: Jahr wird benoetigt.';
  RSNameIsRequired          = 'Fehler: Name kann nicht leer sein.';
  RSFailToCreateTask        = 'Fehler: Fehler beim erzeugen des Termins.';
  RSFailToCreateEvent       = 'Fehler: Failure while creating Event.';
  RSFailToCreateContact     = 'Fehler: Fehler beim erzeugen des Kontaktes.';
  RSFailToCreateResource    = 'Fehler: Fehler beim erzeugen des Resource.';
  RSDuplicateResource       = 'Fehler: doppelter Eintrag.';
  RSInvalidTableSpecified   = 'Fehler: Invalid table specified.';
  RSUnableToOpen            = 'Fehler: kann nicht Oeffnen ';
  RSSQLUpdateError          = 'Fehler: kann nicht aktualisieren ';                {!!.01}

  RSPhoneTypeLabel1         = 'Assistent';
  RSPhoneTypeLabel2         = 'Callback';
  RSPhoneTypeLabel3         = 'Auto';
  RSPhoneTypeLabel4         = 'Firma';
  RSPhoneTypeLabel5         = 'Privat';
  RSPhoneTypeLabel6         = 'Privat Fax';
  RSPhoneTypeLabel7         = 'ISDN';
  RSPhoneTypeLabel8         = 'Mobil';
  RSPhoneTypeLabel9         = 'Andere';
  RSPhoneTypeLabel10        = 'Other Fax';
  RSPhoneTypeLabel11        = 'Pager';
  RSPhoneTypeLabel12        = 'Primary';
  RSPhoneTypeLabel13        = 'Radio';
  RSPhoneTypeLabel14        = 'Telex';
  RSPhoneTypeLabel15        = 'TTY/TDD';
  RSPhoneTypeLabel16        = 'Arbeit';
  RSPhoneTypeLabel17        = 'Arbeit Fax';

  RSHomeAddressLabel        = 'Privat';
  RSWorkAddressLabel        = 'Arbeit';

  RSHomeEmailLabel          = 'Privat';
  RSWorkEMailLabel          = 'Arbeit';
  RSOtherEMaillabel         = 'Andere';

  RSPersonalWebSiteLabel    = 'Personal';
  RSBusinessWebSiteLabel    = 'Geschaeft';

  RSCategoryLabel1          = 'Geschaeft';
  RSCategoryLabel2          = 'Kunden';
  RSCategoryLabel3          = 'Familie';
  RSCategoryLabel4          = 'Personal';
  RSCategoryLabel5          = 'Andere';

  RSToday                   = 'Heute';
  RSTomorrow                = 'Morgen';
  RSNextDay                 = 'Naechster Tag';
  RSNextWeek                = 'Naechste Woche';
  RSNextMonth               = 'Naechstes Monat';
  RSNextYear                = 'Naechstes Jahr';
  RSYesterday               = 'Gestern';
  RSPrevDay                 = 'Tag zurueck';
  RSPrevWeek                = 'Letzte Woche';
  RSPrevMonth               = 'Letztes Monat';
  RSPrevYear                = 'Letztes Jahr';

  RSLow                     = 'Niedrig';
  RSNormal                  = 'Normal';
  RSHigh                    = 'Hoch';

  RSWeekOf                  = 'Woche von';
  RSThrough                 = 'Durch';
  RSSunday                  = 'Sonntag';
  RSMonday                  = 'Montag';
  RSTuesday                 = 'Dienstag';
  RSWednesday               = 'Mittwoch';
  RSThursday                = 'Donnerstag';
  RSFriday                  = 'Fritag';
  RSSaturday                = 'Samstag';
  RSASunday                 = 'So';
  RSAMonday                 = 'Mo';
  RSATuesday                = 'Di';
  RSAWednesday              = 'Mi';
  RSAThursday               = 'Do';
  RSAFriday                 = 'Fr';
  RSASaturday               = 'Sa';
  RSLSunday                 = 'So';
  RSLMonday                 = 'Mo';
  RSLTuesday                = 'Di';
  RSLWednesday              = 'Mi';
  RSLThursday               = 'Do';
  RSLFriday                 = 'Fr';
  RSLSaturday               = 'Sa';
  RSNone                    = '-';
  RSDaily                   = 'Taeglich';
  RSWeekly                  = 'Woechentlich';
  RSMonthlyByDay            = 'Monatlich (Wochentag)';
  RSMonthlyByDate           = 'Monatlich (Tag)';
  RSYearlyByDay             = 'Jaehrlich (Wochentag)';
  RSYearlyByDate            = 'Jaehrlich (Tag)';
  RSCustom                  = 'Benutzerdefiniert';
  RSMinutes                 = 'Minuten';
  RSHours                   = 'Stunden';
  RSDays                    = 'Tage';
  RSWeeks                   = 'Wochen';
  RSMonths                  = 'Monate';
  RSYears                   = 'Jahre';
  RSCalendarWeekAbbr        = 'KW';   // Abbreviation of "calendar week"

  RSAllDay                  = 'Jeden Tag';

  {WARNINGS}
  RSPermanent               = 'Dieser Vorgang kann nicht rueckgaengig gemacht werden !';

  {Contact Specific}
  RSFromContactList         = 'aus Ihrer Kontaktliste wirklich loeschen ?';
  RSContactPopupAdd         = 'neuer Kontakt ...';
  RSContactPopupEdit        = 'Kontakt bearbeiten ...';
  RSContactPopupDelete      = 'Kontakt loeschen ...';
  RSConfirmDeleteContact    = 'Loesche Kontakt %s?';

  {Event Specific}
  RSEvent                   = 'Event';
  RSFromSchedule            = 'aus Ihrer Terminplanung wirklich loeschen ?';
  RSStartEndTimeError       = 'Falsche Reihenfolge der Start- und Endzeiten. ' +
                              'Willst du sie umdrehen?';
  RSCannotEditOverlayedEvent= 'Dieses ueberlagerte Ereignis kann nicht bearbeitet werden.';
  RSOverlayedEvent          = 'ueberlagert';
  RSOverlayed               = 'Ueberlagert';
  RSConfirmDeleteEvent      = 'Ereignis aus Zeitplan loeschen?';

  RSNoOverlayedEvents       = 'keine';

  {Task Specific}
  RSFromTaskList            = 'aus Ihrer Aufgabenliste wirklich loeschen ?';
  RSTaskPopupAdd            = 'Aufgabe hinzufuegen ...';
  RSTaskPopupEdit           = 'Aufgabe bearbeiten ...';
  RSTaskPopupDelete         = 'Aufgabe loeschen ...';
  RSTaskTitleResource       = 'Aufgabenliste - ';                        {!!.01}
  RSTaskTitleNoResource     = 'Aufgabenliste';                           {!!.01}
  RSConfirmDeleteTask       = 'Diese Aufgabe aus Ihrer Liste loeschen?';

  { Popup specific }
  RSPopupAddEvent           = 'Ereignis hinzufuegen...';
  RSPopupEditEvent          = 'Ereignis bearbeiten...';
  RSPopupDeleteEvent        = '&Ereignis loeschen...';
  RSPopupChangeDate         = 'Datum aendern';
  RSPopupResourceGroups     = 'Ueberlagerungsereignisse';

  {Month Specific}
  RSMonthPopupToday         = 'Heute';
  RSMonthPopupNextMonth     = 'naechster Monat';
  RSMonthPopupPrevMonth     = 'vorheriger Monat';
  RSMonthPopupNextYear      = 'naechstes Jahr';
  RSMonthPopupPrevYear      = 'vorheriges Jahr';

  {Week Specific}
  RSWeekPopupAdd            = 'neuer Termin ...';
  RSWeekPopupEdit           = 'Termin bearbeiten ...';
  RSWeekPopupDelete         = 'Termin loeschen ...';
  RSWeekPopupNav            = 'Datum aendern';
  RSWeekPopupNavToday       = 'Heute';
  RSWeekPopupNavNextWeek    = 'naechste Woche';
  RSWeekPopupNavPrevWeek    = 'vorherige Woche';
  RSWeekPopupNavNextMonth   = 'naechster Monat';
  RSWeekPopupNavPrevMonth   = 'vorheriger Monat';
  RSWeekPopupNavNextYear    = 'naechstes Jahr';
  RSWeekPopupNavPrevYear    = 'vorheriges Jahr';

  { Print Preview Specific }
  RSPrintPrvPrevPage        = 'vorherige Seite';
  RSPrintPrvNextPage        = 'naechste Seite';
  RSPrintPrvFirstPage       = 'erste Seite';
  RSPrintPrvLastPage        = 'letzte Seite';
  RSPrintPrvPrint           = '&Drucken';
  RSPrintPrvPrintHint       = 'Drucken';
  RSPrintPrvFirstPageHint   = 'Gehe zur ersten Seite';
  RSPrintPrvPrevPageHint    = 'Gehe zur vorherigen Seite';
  RSPrintPrvNextPageHint    = 'Gehe zur naechsten Seite';
  RSPrintPrvLastPageHint    = 'Gehe zur letzen Seite';
  RSPrintPrvCancel          = 'Abbrechen';
  RSPrintPrvCancelHint      = 'Vorschau abbrechen';

  { DayView Specific }
  RSDayPopupAdd             = 'neuer Termin ...';
  RSDayPopupEdit            = 'Termin bearbeiten ...';
  RSDayPopupDelete          = 'Termin loeschen ...';
  RSDayPopupNav             = 'Datum aendern';
  RSDayPopupNavToday        = 'Heute';
  RSDayPopupNavTomorrow     = 'Morgen';
  RSDayPopupNavYesterday    = 'Gestern';
  RSDayPopupNavNextDay      = 'naechster Tag';
  RSDayPopupNavPrevDay      = 'vorheriger Tag';
  RSDayPopupNavNextWeek     = 'naechste Woche';
  RSDayPopupNavPrevWeek     = 'vorherige Woche';
  RSDayPopupNavNextMonth    = 'naechster Monat';
  RSDayPopupNavPrevMonth    = 'vorheriger Monat';
  RSDayPopupNavNextYear     = 'naechstes Jahr';
  RSDayPopupNavPrevYear     = 'vorheriges Jahr';
  RSHintToday               = 'Heute';                                   {!!.01}
  RSHintTomorrow            = 'Morgen';                                  {!!.01}
  RSHintYesterday           = 'Gestern';                                 {!!.01}
  RSHintNextWeek            = 'naechste Woche';                           {!!.01}
  RSHintPrevWeek            = 'vorherige Woche';                         {!!.01}

  { field names }
  RSPosition                = 'Position';
  RSCompany                 = 'Firma';
  RSTitle                   = 'Titel';
  RSEMail                   = 'E-Mail';
  RSCountry                 = 'Land';
  RSCategory                = 'Beschriftung';
  RSNotes                   = 'Notizen';
  RSLocation                = 'Ort';

  RSCustom1                 = 'Benutzerdefiniert 1';
  RSCustom2                 = 'Benutzerdefiniert 2';
  RSCustom3                 = 'Benutzerdefiniert 3';
  RSCustom4                 = 'Benutzerdefiniert 4';

  { Generic Dialog Captions }
  RSOKBtn                   = 'OK';
  RSCancelBtn               = 'Abbrechen';
  RSCloseBtn                = '&Schliessen';
  RSPrintBtn                = '&Drucken';
  RSUntitled                = 'unbenannt';

  {Sound Selection Dialog}
  RSSelectASound            = 'Sound auswaehlen';
  RSSoundFinder             = 'Sound suchen';
  RSDefaultSound            = 'Default-Sound verwenden';
  RSNothingToSelectFrom     = 'Es ist nichts auszuwaehlen, wenn der Standardton verwendet wird. ';

  { Event Edit Dialog Captions }
  RSDlgEventEdit            = 'Termin';
  RSAppointmentGroupBox     = 'Allgemein';
  RSDescriptionLbl          = 'Betreff:';
  RSLocationLbl             = 'Ort:';
  RSCategoryLbl             = 'Kategorie:';
  RSStartTimeLbl            = 'Startzeit:';
  RSEndTimeLbl              = 'Endzeit:';
  RSAlarmSet                = '&Erinnerung';
  RSRecurringLbl            = 'Serienmuster:';
  RSIntervalLbl             = 'Intervall (Tage):';
  RSRecurrenceEndsLbl       = 'Wiederholen bis:';
  RSAllDayEvent             = '&ganztaegig';
  RSNotesLbl                = 'Notizen:';

  { Contact Edit Dialog Captions }
  RSDlgContactEdit          = 'Kontakt';
  RSLastNameLbl             = 'Nachname:';
  RSFirstNameLbl            = 'Vorname:';
  RSNameLbl                 = 'Name:';
  RSTitleLbl                = 'Titel:';
  RSAddressLbl              = 'Addresse:';
  RSCityLbl                 = 'Ort:';
  RSDepartmentLbl           = 'Abteilung:';
  RSStateLbl                = 'Staat:';
  RSCountryLbl              = 'Bundeslang:';
  RSZipCodeLbl              = 'PLZ:';
  RSCompanyLbl              = 'Forma:';
  RSPositionLbl             = 'Position:';
  RSPhoneFax                = 'Telefon/Fax';
  RSWebsites                = 'Webseiten';
  RSBirthDateLbl            = 'Geburtstag:';
  RSAgeLbl                  = 'Age:';
  RSAnniversaryLbl          = 'Jahrestag:';
  RSUppercaseContact        = 'KONTAKT';
  RSUppercaseHOME           = 'PRIVAT';
  RSUppercaseWORK           = 'ARBEIT';
  RSUppercaseCUSTOM         = 'BENUTZERDEFINIERT';
  RSUppercaseNOTES          = 'NOTIZEN';

  RSMasterData              = 'Stammdaten';
  RSAddresses               = 'Adressen';
  RSWorkAddress             = 'Arbeitsadresse';
  RSHomeAddress             = 'Privatadresse';

  { Print Preview dialog captions }
  RSDlgPrintPreview        = 'Druckvorschau';

  { Task Edit Dialog Captions }
  RSDlgTaskEdit            = 'Aufgabe';
  RSTaskComplete           = 'Aufgabe abgeschlossen';
  RSDueDate                = 'faellig bis:';
  RSDetails                = 'Details:';
  RSComplete               = 'erledigt';
  RSDaysOverdue            = ' Tage ueberfaellig';
  RSDueDateLabel           = 'faellig bis:';
  RSCreatedOn              = 'Erstellt am';
  RSCompletedOn            = 'Fertig am';
  RSPriorityLabel          = 'Prioritaet:';
  RSCategoryLabel          = 'Kategorie:';

  { Resource Edit Dialog Captions }
  RSDlgResEditCaption       = 'Ressource bearbeiten';
  RSDlgResEditDescription   = 'Beschreibung';
  RSResource                = 'Ressource';

  { Reminder Dialog Captions}
  RSReminder               = 'Erinnerung';
  RSOverdue                = 'UeBERFAeLLIG!';
  RSSnoozeCaption          = 'erneute &Erinnerung in:';
  RSSubjectCaption         = 'Betreff:';
  RSNotesCaption           = 'Notizen:';
  RSDismissBtn             = '&Schliessen';
  RSSnoozeBtn              = '&Erinnerung';
  RSOpenItemBtn            = 'oeffne Eintrag';
  RS1Minute                 = '1 Minute';
  RS5Minutes               = '5 Minuten';
  RS10Minutes              = '10 Minuten';
  RS15Minutes              = '15 Minuten';
  RS30Minutes              = '30 Minuten';
  RS45Minutes              = '45 Minuten';
  RSXMinutes                = '%d Minuten';
  RS1Hour                  = '1 Stunde';
  RS2Hours                 = '2 Stunden';
  RS3Hours                 = '3 Stunden';
  RS4Hours                 = '4 Stunden';
  RS5Hours                 = '5 Stunden';
  RS6Hours                 = '6 Stunden';
  RS7Hours                 = '7 Stunden';
  RS8Hours                 = '8 Stunden';
  RSXHours                  = '%d Stunden';
  RS1Days                  = '1 Tag';
  RS2Days                  = '2 Tagen';
  RS3Days                  = '3 Tagen';
  RS4Days                  = '4 Tagen';
  RS5Days                  = '5 Tagen';
  RS6Days                  = '6 Tagen';
  RS1Day                    = '1 Tag';
  RSXDays                   = '%d Tage';
  RS1Week                  = '1 Woche';

  { Print Format Item Editor }
  RSEditFormatCaption       = 'Format bearbeiten';
  RSTimeIncLbl              = 'Zeitinkrement:';
  RSTimeIncUnits            = 'Zeitinkrementeinheiten:';

  { Calendar }
  RSCalendarPrevMonth      = 'vorheriger Monat';
  RSCalendarNextMonth      = 'naechster Monat';
  RSCalendarPrevYear       = 'vorheriges Jahr';
  RSCalendarNextYear       = 'naechstes Jahr';
  RSCalendarToday          = 'Heute';
  RSCalendarRevert         = 'Zurueck';

  RSCalendarPopupToday     = 'Heute';
  RSCalendarPopupNextMonth = 'naechster Monat';
  RSCalendarPopupPrevMonth = 'vorheriger Monat';
  RSCalendarPopupNextYear  = 'naechstes Jahr';
  RSCalendarPopupPrevYear  = 'vorheriges Jahr';
  RSCalendarPopupRevert    = 'Zurueck';

  { Ini storage }
  RSIniFileStructure       = 'Falsche Struktur der INI-Datei.';

  { XML }
  sIENotInstalled    = 'Cannot open WININET, Microsoft IE required';
  sOpenFileFailed    = 'Unable to open file ';
  sFileNotFound      = 'File %s could not be found';
  sAllocSrcMemFailed = 'Unable to allocate memory for XML source';
  sHttpReadReqFailed = 'Http read request failed';
  sHttpDataNotAvail  = 'Http data not available';
  sHttpReqSendFailed = 'Unable to send http request';
  sHttpReqOpenFailed = 'Unable to open http request';
  sInetConnectFailed = 'Unable to make Internet connection';
  sInetOpenFailed    = 'Unable to open Internet';
  sInvalidFtpLoc     = 'Invalid ftp location';
  sInvalidFtpDir     = 'Invalid ftp directory';
  sFtpReadReqFailed  = 'Ftp read request failed';
  sFtpDataNotAvail   = 'Ftp data not available';
  sFtpOpenFileFailed = 'Unable to open ftp file';
  sFtpPutFileFailed  = 'Could not save file via ftp to %s';
  sSrcLoadFailed     = 'Unable to load source ';
  sInvalidMemPtr     = 'Invalid memory Pointer';
  sFmtErrorMsg       = 'Line: %d Col: %d Error: %s';
  sIndexOutOfBounds  = 'ERROR INDEX OUT OF BOUNDS';
  sExpMarkupDecl     = 'Expected markup declaration, but found: ';
  sIllAttrType       = 'Illegal attribute type: ';
  sIllAttrDefKeyw    = 'Illegal keyword for attribute default value: ';
  sSysIdMissing      = 'System identifier missing ';
  sExtModifMissing   = 'External modifier missing: ';
  sIllCondSectStart  = 'Conditional section must begin with INCLUDE or IGNORE';
  sBadSepInModel     = 'Bad separator in content model: ';
  sExpCommentOrCDATA = 'Expected comment or CDATA section ';
  sUnexpectedEof     = 'Unexpected end of file ';
  sMismatchEndTag    = 'Mismatched end tag: ';
  sIllCharInRef      = 'Illegal character in reference';
  sUndeclaredEntity  = 'Reference to undeclared entity: ';
  sExpectedString    = 'Expected String: ';
  sSpaceExpectedAt   = 'Whitespace expected at byte ';
  sUnexpEndOfInput   = 'End of input while looking for delimiter: ';
  sQuoteExpected     = 'Expected " or ' + Chr (39);
  sInvalidXMLVersion = 'XMLPartner does not support XML specification greater than %s';
  sUnableCreateStr   = 'Unable to create stream for input.';
  sInvalidName       = 'Invalid XML name: ';
  sInvalidCommentText= 'Invalid comment text';
  sCommentBeforeXMLDecl = 'Document cannot start with a comment if it also contains an XML declaration';
  sInvalidCDataSection = 'Invalid characters in CDATA section';
  sRedefinedAttr     = 'Attributes cannot be redefined in a start tag';
  sCircularEntRef    = 'Circular reference to: ';
  sInvAttrChar       = 'Invalid character in attribute value: ';
  sInvPCData         = 'Invalid characters in element''s character data: ';
  sDataAfterValDoc   = 'There is invalid data after valid XML document';
  sNoIntConditional  = 'Conditional sections not allowed in internal subset of document type declaration';
  sNotationNotDeclared = 'Notation not declared: ';
  sInvPubIDChar      = 'Invalid PublicID character: ';
  sNoNDATAInPeDecl   = 'NDATA not allowed in parameter entity declaration';
  sInvStandAloneVal  = 'Standalone value must equal ''yes'' or ''no''';
  sInvEncName        = 'Invalid encoding declaration: ';
  sInvVerNum         = 'Invalid XML version number: ';
  sInvEntityValue    = 'Invalid character in entity value: ';
  sNoCommentInMarkup = 'Comments can not be placed within other markup';
  sNoPEInIntDTD      = 'Parameter entities not allowed in DTD internal subset';
  sXMLDecNotAtBeg   =  'The XML declaration must appear before the first element';
  sInvalidElementName = 'Invalid element name: ';
  sBadParamEntNesting = 'Parameter-entity text must be properly nested: ';
  sInvalidCharEncoding = 'Invalid character encoding specified.';
  sAttrNotNum        = 'Attribute %s of element %s does not have an integer value.';
  sUnknownAxis       = 'Unknown axis specifier: %s';

  {xpchrstm related errors}
  sInvalidXMLChar    = 'Invalid XML Character found';
  sInvalidBEChar     = 'Invalid (big-endian) UTF-16 character encoding';
  sInvalidLEChar     = 'Invalid (little-endian) UTF-16 character encoding';
  sBadUTF8Char       = 'Badly formed UTF-8 character in stream';
  sErrEndOfDocument  = 'Unexpected end of document stream';
  sUCS_ISOConvertErr = 'Cannot convert UCS-4 character to ISO-8859-1';
  sUCS_U16ConvertErr = 'Cannot convert UCS-4 character to UTF-16';
  sUCS_U8ConverErr   = 'Cannot convert UCS-4 character to UTF-8';

  { Misc Exceptions and Errors }

  RSOutOfRange       = 'Out of range';
  RSNotSupported     = 'not supported';
  RSNeedElementName  = 'Please supply an Element Name';
  RSNeedFormatName   = 'FormatName cannot be blank';
  RSPrtControlOwner  = 'Print controller is not owned by a TVpControlLink!';
  RSBadPrintFormat   = 'Invalid print format ';
  RSBadItemType      = 'Invalid item type ';
  RSBadMeasurement   = 'Invalid measurement';
  RSOwnerNotWinCtrl  = 'Owner must be a TWinControl descendent';
  RSNoControlLink    = 'Component must be linked to a TVpControlLink';
  RSNoPrintFormats   = 'No print formats have been defined';             {!!.01}
  RSNoCanvas         = 'TCanvas not assigned';                           {!!.01}
  RSNoLocalizationFile = 'Localization file not found.';                 {!!.02}

  { Misc strings }

  RSCategoryDesc0    = 'Kategorie 0';                                     {!!.01}
  RSCategoryDesc1    = 'Kategorie 1';                                     {!!.01}
  RSCategoryDesc2    = 'Kategorie 2';                                     {!!.01}
  RSCategoryDesc3    = 'Kategorie 3';                                     {!!.01}
  RSCategoryDesc4    = 'Kategorie 4';                                     {!!.01}
  RSCategoryDesc5    = 'Kategorie 5';                                     {!!.01}
  RSCategoryDesc6    = 'Kategorie 6';                                     {!!.01}
  RSCategoryDesc7    = 'Kategorie 7';                                     {!!.01}
  RSCategoryDesc8    = 'Kategorie 8';                                     {!!.01}
  RSCategoryDesc9    = 'Kategorie 9';                                     {!!.01}

  { Misc strings }
  RSCategoryDesc     = 'Kategorie %d';

  { Print Format Editor }

  RSPrintFormatDesigner     = 'Druckformat-Designer';
  RSEditPrintFormat         = 'bearbeite Drucklayout...';
  RSFormatLbl               = 'Format:';
  RSFormats                 = 'Formate:';
  RSElements                = 'Elemente:';
  RSNewBtn                  = 'Neu';
  RSEditBtn                 = 'Bearbeiten';
  RSDeleteBtn               = 'Loeschen';
  RSPrintOrder              = 'Druckrehenfoge';
  RSNewFileBtn              = 'Neue Datei';
  RSLoadFileBtn             = 'Datei laden...';
  RSSaveFileBtn             = 'Datei speichern...';

  RSReportSetup             = 'Druckereinstellungen';

  { Format element editor }
  RSEditElementCaption      = 'Elemet bearbeiten';
  RSElementTypeLbl          = 'Elementtyp';
  RSDayViewElement          = 'Tagesansicht';
  RSWeekViewElement         = 'Wochenansicht';
  RSMonthViewElement        = 'Monatsansicht';
  RSCalendarElement         = 'Kalender';
  RSShapeElement            = 'Form';
  RSCaptionElement          = 'Bildbeschriftung';
  RSTasksElement            = 'Aufgaben';
  RSContactsElement         = 'Kontakte';
  RSVisualCaption           = 'Visuell';
  RSRotationCaption         = 'Rotation';
  RSMeasurementCaption      = 'Messung';
  RSPixels                  = 'Pixels';
  RSPercent                 = 'Prozent';
  RSInches                  = 'Inches';
  RSLeft                    = 'Links';
  RSTop                     = 'Oben';
  RSWidth                   = 'Breite';
  RSHeight                  = 'Hoehe';
  RSVisible                 = 'Sichtbar';
  RSCaption                 = 'Bildbeschriftung';
  RSTextCaption             = 'Text';
  RSShapeBtn                = 'Form...';
  RSFontBtn                 = 'Schriftart...';

  { Shape editor }
  RSEditShapeCaption        = 'Form bearbeiten';
  RSShapeCaption            = 'Form';
  RSRectangle               = 'Rechteck';
  RSTopLine                 = 'oberste Zeile';
  RSBottomLine              = 'untere Zeile';
  RSLeftLine                = 'linke Zeile';
  RSRightLine               = 'rechte Zeile';
  RSTLToBRLine              = 'obere linke bis untere rechte Zeile';
  RSBLToTRLine              = 'Zeile von links unten nach rechts oben';
  RSEllipse                 = 'Ellipse';
  RSPenCaption              = 'Stift';
  RSBrushCaption            = 'Pinsel';
  RSStyleLbl                = 'Stil:';
  RSWidthLbl                = 'Breite:';
  RSModeLbl                 = 'Modus:';
  RSColorLbl                = 'Farbe:';

  { Automatic resource adding/selection}                               {!!.01}

  RSAddNewResource   = 'No resources have been defined. Would you ' +  {!!.01}
                       'like to add one now?';                         {!!.01}
  RSSelectResource   = 'No resource has been selected. Would you ' +   {!!.01}
                       'like to select one now?';
